CREATE TABLE IF NOT EXISTS person (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    role INTEGER NOT NULL,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS slot (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    person_id INTEGER,
    date TEXT NOT NULL,
    hour INTEGER NOT NULL,
    FOREIGN KEY (person_id) REFERENCES person (id)
);
